process.env.NODE_ENV = 'test';
process.env.DATABASE_URL =
  process.env.TEST_DATABASE_URL ??
  'postgresql://beautyflow:beautyflow_dev@localhost:5433/beautyflow_test?schema=public';
process.env.REDIS_URL ??= 'redis://localhost:6379';
process.env.JWT_ACCESS_SECRET ??= 'test-access-secret-at-least-32-characters-long';
process.env.JWT_REFRESH_SECRET ??= 'test-refresh-secret-at-least-32-characters-long';
process.env.ACCESS_TOKEN_TTL ??= '15m';
process.env.REFRESH_TOKEN_TTL ??= '30d';
process.env.LOG_LEVEL = 'log';
process.env.SMTP_HOST ??= 'email-smtp.us-east-1.amazonaws.com';
process.env.SMTP_PORT ??= '587';
process.env.SMTP_SECURE ??= 'false';
process.env.SMTP_REQUIRE_TLS ??= 'true';
process.env.SMTP_USER ??= 'test-smtp-user';
process.env.SMTP_PASSWORD ??= 'test-smtp-password';
process.env.SMTP_FROM ??= 'no-reply@example.com';
process.env.MAIL_FROM_NAME ??= 'BeautyFlow';
process.env.APP_PUBLIC_URL ??= 'http://localhost:3001';
process.env.INVITATION_EXPIRY_HOURS ??= '48';
